# Generated by Django 4.0.3 on 2022-04-10 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목 없음')),
                ('detail', models.TextField(verbose_name='내용 없음')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 10, 7, 17, 5, 856637, tzinfo=utc))),
                ('d_day', models.DateField(default=datetime.datetime(2022, 4, 10, 7, 17, 5, 856840, tzinfo=utc))),
            ],
        ),
    ]
