# Generated by Django 4.0.3 on 2022-04-11 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0003_alter_post_d_day_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='d_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
